### PR TITLE
Prioritize preset arguments over global arguments

### PR DESCRIPTION
**Pull request by charlesthobe**
Also added lowercase "/build*" to .gitignore

### CODE REVIEW

**Comment by charlesthobe** [comment]
Rational; when having arguments with different parameters, the latter arguments take precedence over the earlier ones.

e.g running `gzdoom +fluid_patchset soundfont1.sf2 +fluid_patchset soundfont2.sf2` sets fluid_patchset to soundfont2.sf2

And a user might want to set an argument globally to something then to something else for some presets.

**Comment by charlesthobe** [comment]
Rational; when having arguments with different parameters, the latter arguments take precedence over the earlier ones.

e.g running `gzdoom +fluid_patchset soundfont1.sf2 +fluid_patchset soundfont2.sf2` sets fluid_patchset to soundfont2.sf2

And a user might want to set an argument globally to something then to something else for some presets.

**Review by Youda008 — APPROVED** [review]
Sounds good, thank you! 🙂

**Comment by charlesthobe** [comment]
You're welcome

**Pull request merged**
