### PR TITLE
Fix compiler error on Mac, add build instructions and icon.

### PR DESCRIPTION
**Pull request by jakestanley**
Hi. I love DoomRunner. I've been using it for a couple of years now. Anyway, it turned out a lot easier than expected to get it building, it was just that templating error. I have compiled and run it successfully on both Intel and ARM, but there will be no universal binary build due to that being a commercial Qt feature. Please take a look, I would be happy to provide release builds for both platforms. Thanks

### CODE REVIEW

**Review by Youda008 — APPROVED** [review]
Awesome! Thanks a lot 🤝

**Comment by jakestanley** [comment]
I have attached builds for the most recent master #4a61c9a
I am happy to build again for the next release
[DoomRunner (Apple Silicon).app.zip](https://github.com/Youda008/DoomRunner/files/12843885/DoomRunner.Apple.Silicon.app.zip)
[DoomRunner (Intel).app.zip](https://github.com/Youda008/DoomRunner/files/12843886/DoomRunner.Intel.app.zip)

**Comment by jakestanley** [comment]
@Youda008 here are the Mac builds for #4a61c9a. 
I am happy to provide for the next release. Thanks for accepting:
[DoomRunner_Mac.zip](https://github.com/Youda008/DoomRunner/files/12843931/DoomRunner_Mac.zip)

**Comment by Youda008** [comment]
Hi @jakestanley. I'm about to release 1.8.2 soon. Could you please try if the build still works, and possibly do some basic functionality test?
Most importantly, i would need to test this piece of code https://github.com/Youda008/DoomRunner/blob/master/Sources/Utils/OSUtils.cpp#L299 because i have never tested it before, as i don't have a Mac to test on.
You can trigger this function by right-clicking any mod file and selecting "Open File Location", or by pressing the new button next to the engine list on the main tab.

**Pull request merged**
