### PR TITLE
Generalize desktop file

### PR DESCRIPTION
**Pull request by mbugni**
See also https://github.com/Youda008/DoomRunner/issues/114

### CODE REVIEW

**Comment by Youda008** [comment]
Can you rebase on the current master? I believe the line 3 change is a product of my own recent changes.

**Comment by Youda008** [comment]
Also, cc @poperigby

**Comment by mbugni** [comment]
> Also, cc @poperigby This might break your package.

Yes, I forgot to mention https://github.com/Youda008/DoomRunner/pull/65

**Comment by mbugni** [comment]
> Can you rebase on the current master? I believe the line 3 change is a product of my own recent changes.

Would you like to change the description?

**Comment by Youda008** [comment]
I would like to keep the one currently in my repository. I'm also about to change it in the README.

**Comment by mbugni** [comment]
> I would like to keep the one currently in my repository. I'm also about to change it in the README.

Ok, so do you want me to close the PR?
Changes are about:
- description (closer to the README one)
- icon name (because PNG are provided)
- additional keywords (for search helping)

**Comment by Youda008** [comment]
No, i wanted you to revert that one unwanted (possibly accidental) change.
Never mind, i will do it manually.

**Pull request merged**
