### PR TITLE
Add .desktop file for Linux

### PR DESCRIPTION
**Pull request by poperigby**

### CODE REVIEW

**Comment by Youda008** [comment]
Ok i have no idea what this does, so i trust you that it's correct.

**Review by Youda008 — APPROVED** [review]

**Comment by poperigby** [comment]
> Ok i have no idea what this does, so i trust you that it's correct.

Thanks lol. It's basically the same think as a start menu entry on Windows.

**Comment by Youda008** [comment]
@poperigby I have a question regarding the application icon. This file point to an icon in `/usr/share/icons/doomrunner.ico` but the project file doesn't specify any rule for installing the icon file into this location. How does the icon get there? Shouldn't that also be added?

**Comment by poperigby** [comment]
I was copying the icon file with the AUR package manifest. I think it's best to leave the PKGBUILD doing that job, but I'm open to changing it.

**Comment by Youda008** [comment]
Ok, but shouldn't the desktop file then be also part of the AUR package? It looks strange that there is a file in my repository that points to something that is not installed.

**Comment by mbugni** [comment]
It could be useful to have a common template (application name, description, etc) for every Linux distribution channel, since a standard exists. I suggest to put Linux desktop files (.desktop, icons etc) in one place, for example `Resources/XDG`. Maintainers will take care to pick them from sources and to put them in the right place with the right name. If patches are needed, they can be applied during packaging process.

Icon names, in desktop entries, can be relative (no path, no extension), see [1]. 
I already provided a full icon set (see [2]). We can follow Flatpak recommendations [3], that are fine for modern desktops:
> Applications must provide application icons in at least 64×64px and 128×128px sizes. Application icons should either be included as scalable SVGs or high-resolution PNGs

[1] https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html
[2] https://github.com/Youda008/DoomRunner/issues/108
[3] https://github.com/flathub/flathub/wiki/App-Requirements

**Comment by mbugni** [comment]
> /usr/bin/qmake -install qinstall -exe DoomRunner /usr/bin/DoomRunner
Error copying DoomRunner to /usr/bin/DoomRunner: Cannot create /usr/bin/DoomRunner for output
make: *** [Makefile:1620: install_target] Error 3

I found a workaround for this:
```yaml
- name: doomrunner-build
    buildsystem: qmake
    builddir: true
    make-opts:
      - CONFIG+=release
    make-install-args:
      - INSTALL_ROOT+=/app/tmp
    sources:
      - type: git
        url: https://github.com/Youda008/DoomRunner
        branch: master
    post-install:
      - mv /app/tmp/usr/bin/DoomRunner /app/bin/DoomRunner
      - rm /app/tmp -rf
```
It's a bit dirty, but I can survive.
But I'm facing another problem, it seems that the launcher doesn't prefix the command with `flatpak-spawn --host`, isn't it?

**Comment by Youda008** [comment]
Alright. I have created a directory for OS-specific files to be installed and moved the `.desktop` file and png icon files there.
Package maintainers will need to patch those if needed and then install them into proper directories.

**Pull request merged**
