### PR TITLE
Add scoop installation method

### PR DESCRIPTION
**Pull request by sitiom**
I have just added DoomRunner to Scoop, and I am adding a reference to it here.

### CODE REVIEW

**Comment by sitiom** [comment]
@Youda008 bump

**Comment by Youda008** [comment]
What is Scoop by the way?

**Comment by sitiom** [comment]
A package manager for Windows: https://scoop.sh/. [`doomrunner`](https://scoop.sh/#/apps?q=doomrunner&s=0&d=1&o=true)

**Comment by Youda008** [comment]
Oh nice.

**Review by Youda008 — APPROVED** [review]

**Pull request merged**
